### ISSUE TITLE
nonissue but request to add your code or .dll to our project

### ISSUE THREAD

**Issue by MicahMoo11** [ayuanx/pal-ddraw#2]
this is related to this issue https://github.com/narzoul/DDrawCompat/issues/311

basically, DirectDraw from Vista-11 are showing deterioration with old games that rely upon DirectDraw from windows 9x.

with our custom patches, we have been working on it sense May 2021 with our email proof, below. ideally, we prefer DDrawCompat, but your code is good enough for windows 2000, XP and early Vista (also longhorn). even 11
can we add this to our source code. although, some games like cluefinders just works so no changes on our end.

[DirectDrew issue email..odt](https://github.com/ayuanx/pal-ddraw/files/15265514/DirectDrew.issue.email.odt)

**Comment by ayuanx** [comment]
This project is open source, so as long as you follow the license, you can use it anywhere.
