### ISSUE TITLE
certain the learning company may not work with full screen without enabling  ScriptDebug=1

### ISSUE THREAD

**Issue by MicahMoo11** [ayuanx/pal-ddraw#3]
Hello ayuanx this is not a bug report, this is information for your future improvements for the games

They is a bug with your code will unsafely kill the process under full screen mode. With certain the learning company games.

Here is the code we made for the games to accommodate your code that we found.

[Fifth Grade Adventures - CD]
CDDrive=
UseDirectDraw=1
DisplayFullScreen=0
ScriptDebug=1
altDance=1

you might notice DisplayFullScreen=0. By default the game is in force windowed mode. for some reason your full screen conflicts with the games engine with your ddraw.dll. What we did was we program the game by using ScriptDebug=1. To tell the game always force windowed mode which is not supported by the game engine that fixed the conflicts with ddraw.dll

We did attempt to fix with DisplayFullScreen=1 although it was causing other problems on our end. like showing discoloration due to 16-bit colors, which conflicts our code for forcing 32-bit colors. So, we kept windowed mode for compatibility. 

However they is some games like RR 4.0 Math 4-6_v11 or reader rabbit math 4-6. does not support ScriptDebug=1 as it was removed from the final product. We restored it with limitations. 

We did fix it but it is odd to us even with unaltered original the learning company will behavior like this without forcing windowed mode for some reason. even worse some games no longer have ScriptDebug=1 without modifications. even if it does most users may not be away of its existence. even if they did, they have to rewrite setup.ini which is no easy feat for most users.

**Comment by ayuanx** [comment]
Please read the **readme.txt**.

> Currently only full screen mode emulation is implemented. Window mode emulation is not supported yet.

**Comment by MicahMoo11** [comment]
this is fine like we said all 47 the learning company is already on Windowed mode.
that is why your code for pal-ddraw worked. now we don't understand why forcing windowed mode on them
fixed it, but it did. that is why we said

Hello ayuanx this is not a bug report, this is information for your future improvements for the games
